### ISSUE TITLE
Key error when run

### ISSUE THREAD

**Issue by DanielBrett** [aliparlakci/bulk-downloader-for-reddit#243]
Hi guys,

I followed the instructions [here](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/INTERPRET_FROM_SOURCE.md) but when I try to run I get the following errors.
```
ERROR:root:KeyError
Traceback (most recent call last):
  File "script.py", line 374, in <module>
    main()
  File "script.py", line 273, in main
    sys.argv = sys.argv + GLOBAL.config["options"].split()
KeyError: 'options'

Traceback (most recent call last):
  File "script.py", line 387, in <module>
    if not GLOBAL.arguments.quit:
AttributeError: 'NoneType' object has no attribute 'quit'
```

I am not sure where to start troubleshooting this.

Thanks,

Daniel

**Comment by AnonymousCondor** [comment]
I can't say if this is any kind of permanent fix, but what worked for me was to delete the directory with the default configuration file in it (Note: I'm not sure if actually doing this part makes a difference or not, but thought I would add it since it was part of the steps that worked for me AND of course if you changed the config file this will erase it) and then adding back in this block of code at the top of the main() function in script.py:

```
    if Path("config.json").exists():
        GLOBAL.configDirectory = Path("config.json")
    else:
        if not Path(GLOBAL.defaultConfigDirectory).is_dir():
            os.makedirs(GLOBAL.defaultConfigDirectory)
        GLOBAL.configDirectory = GLOBAL.defaultConfigDirectory  / "config.json"
        GLOBAL.configDirectory = GLOBAL.defaultConfigDirectory / "config.json"
    try:
        GLOBAL.config = Config(GLOBAL.configDirectory).generate()
    except InvalidJSONFile as exception:
        VanillaPrint(str(exception.__class__.__name__),">>",str(exception))
        VanillaPrint(str(exception.__class__.__name__), ">>", str(exception))
        VanillaPrint("Resolve it or remove it to proceed")
        input("\nPress enter to quit")
        sys.exit()
```

The default configuration file is usually located in "C:\Users\\{USER}\Bulk Downloader for Reddit" on Windows, not sure where on other operating systems.

Again just want to stress that this was just what worked for me, and I am not sure how if at all this affects the rest of the script. It did make it work for me, however.

**Comment by DanielBrett** [comment]
Hi all,

So this fix worked on my desktop when I tested it but when I put it into a docker container it no longer worked.  I get a new error:

```
ERROR:root:OSError
Traceback (most recent call last):
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/script.py", line 390, in <module>
    main()
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/script.py", line 281, in main
    GLOBAL.config = Config(GLOBAL.configDirectory).generate()
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/src/config.py", line 14, in generate
    self._validateCredentials()
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/src/config.py", line 117, in _validateCredentials
    Reddit().begin()
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/src/reddit.py", line 42, in begin
    reddit, refresh_token = self.getRefreshToken(*self.SCOPES)
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/src/reddit.py", line 82, in getRefreshToken
    client = self.recieve_connection()
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/src/reddit.py", line 57, in recieve_connection
    server.bind(('0.0.0.0', self.PORT))
OSError: [Errno 98] Address already in use

Traceback (most recent call last):
  File "/File-Transfer-to-Port-Repo/bulk-downloader-for-reddit-master/script.py", line 403, in <module>
    if not GLOBAL.arguments.quit:
AttributeError: 'NoneType' object has no attribute 'quit'
```

Any idea why it would not work in a docker container?

Thanks,

Daniel

**Comment by aliparlakci** [comment]
I strongly recommend you to switch to v2 unless you have a specific reason not to.

**Comment by aliparlakci** [comment]
I have pushed a commit to master branch, hopefully, resolving the issue.

**Comment by DanielBrett** [comment]
I tried the newly committed version and still get the same error as the top of the post except that the line numbers are 2 lines less.  Also is V2 functional?  I popped over to that branch to take a look but there were no real instructions on how to set it up.  At least not that I saw.  Just descriptions on how to use the tool after it was set up.  If that tool works better I'd be happy to switch over if anyone could provide some instructions on how to set it up.  

Thanks,

Daniel

**Comment by aliparlakci** [comment]
v2 is fully functional and is going to replace v1 in a week or so.

There are no instructions to set it up because **you don't need to anything to use the commands in the README file**. If you are in the root directory of the project, you can do `python3 -m bulkredditdownloader` and it will just run. 

Soon, bdfr will be published to pip repository and you will be able to install it with `pip install bdfr` The setup.py file is for pip to add bdfr next to the other pip packages. So that you can run `python3 -m bulkredditdownloader` not only from the project's root directory but everywhere in the disk.

Serene-Arc has a great comment on another issue explaining the situation: https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/240#issuecomment-811564407 I suggest you to read the entire comment.

**Comment by DanielBrett** [comment]
Thank you for all of the help!  I have gotten V2 set up and working.  One thing I noticed about the archiving option is that it seems to create a .json file for each item its looks at instead of compiling a single file.  Is there a flag that I missed perhaps that appends all the results into a single file?  Would this question be better as its own seperate issue?

Thanks,

Daniel

**Comment by aliparlakci** [comment]
No, there is no such option. Because, now, every separate json holds more information (comment section) than an entry in a single json file. It would end up being a too large file. It is also browsed easily, this way.If you still want to have a single file, you can achieve it with a simple script.

**Comment by DanielBrett** [comment]
That makes sense!  Thanks for all of your help!
